# Generated by Django 2.0.1 on 2018-08-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charlie',
            old_name='business',
            new_name='kind',
        ),
    ]
