# Generated by Django 2.0.1 on 2018-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0002_auto_20180806_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlie',
            name='kind',
            field=models.CharField(choices=[('brand', 'Brand'), ('agency', 'Agency')], max_length=10),
        ),
    ]
