# Generated by Django 2.0.1 on 2018-08-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_auto_20180806_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charlie',
            name='kind',
            field=models.CharField(choices=[('public_figure', 'Public Figure'), ('community', 'Community'), ('agency', 'Agency'), ('brand', 'Brand')], max_length=20),
        ),
    ]
