# Generated by Django 2.0.1 on 2018-01-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0002_content_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='publisher',
        ),
        migrations.AddField(
            model_name='content',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='social_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
            preserve_default=False,
        ),
    ]
