# Generated by Django 2.0.1 on 2018-01-19 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20180119_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='socialaccount.SocialAccount'),
        ),
    ]
