# Generated by Django 2.0.1 on 2018-01-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('contents', '0006_remove_content_social_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='content',
            old_name='account',
            new_name='user',
        ),
        migrations.AddField(
            model_name='contentsocialaccount',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='contents.Content'),
        ),
        migrations.AddField(
            model_name='contentsocialaccount',
            name='social_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='socialaccount.SocialAccount'),
        ),
    ]
