# Generated by Django 2.0.1 on 2018-01-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('contents', '0007_auto_20180119_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentsocialaccount',
            name='content',
        ),
        migrations.RemoveField(
            model_name='contentsocialaccount',
            name='social_account',
        ),
        migrations.AddField(
            model_name='content',
            name='social_accounts',
            field=models.ManyToManyField(related_name='social_accounts', to='socialaccount.SocialAccount'),
        ),
        migrations.DeleteModel(
            name='ContentSocialAccount',
        ),
    ]
