# Generated by Django 2.0.1 on 2018-01-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20180119_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='social_accounts',
        ),
    ]
