# Generated by Django 2.0.1 on 2018-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('contents', '0009_remove_content_social_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='social_accounts',
            field=models.ManyToManyField(related_name='socials', to='socialaccount.SocialAccount'),
        ),
    ]
