KINDS = (
    ('public_figure', 'Public Figure'),
    ('community', 'Community'),
    ('agency', 'Agency'),
    ('brand', 'Brand'),
)

CATEGORIES = (
    ('books', 'Books'),
    ('business', 'Business'),
    ('education', 'Education'),
    ('entertainment', 'Entertainment'),
    ('finance', 'Finance'),
    ('food & drink', 'Food & Drink'),
    ('games', 'Games'),
    ('health & fitness', 'Health & Fitness'),
    ('kids', 'Kids'),
    ('lifestyle', 'Lifestyle'),
    ('medical', 'Medical'),
    ('music', 'Music'),
    ('navigation', 'Navigation'),
    ('news', 'News'),
    ('photo & video', 'Photo & Video'),
    ('productivity', 'Productivity'),
    ('reference', 'Reference'),
    ('social networking', 'Social Networking'),
    ('shopping', 'Shopping'),
    ('sports', 'Sports'),
    ('travel', 'Travel'),
    ('utilities', 'Utilities'),
    ('weather', 'Weather'),
)