# Generated by Django 2.0.1 on 2018-04-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('multimedia', models.ImageField(blank=True, null=True, upload_to='contents')),
                ('schedule', models.CharField(choices=[('now', 'Now'), ('custom', 'Custom')], default='now', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('schedule_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('picture_url', models.URLField(blank=True)),
                ('access_token_key', models.TextField(max_length=1000)),
                ('access_token_secret', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('profile', 'profile'), ('page', 'page'), ('group', 'group'), ('company', 'company')], default='profile', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='socials',
            field=models.ManyToManyField(to='dashboard.Social'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider', 'account')},
        ),
    ]
