# Generated by Django 2.0.1 on 2018-02-13 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='chosen_socials',
        ),
        migrations.RemoveField(
            model_name='social',
            name='social_links',
        ),
        migrations.AddField(
            model_name='content',
            name='socials',
            field=models.ManyToManyField(to='dashboard.Social'),
        ),
        migrations.AddField(
            model_name='social',
            name='accounts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
