# Generated by Django 2.0.1 on 2018-02-12 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SocialConnected',
            new_name='SocialLink',
        ),
        migrations.RemoveField(
            model_name='content',
            name='socials_connected',
        ),
        migrations.RemoveField(
            model_name='social',
            name='accounts',
        ),
        migrations.AddField(
            model_name='social',
            name='social_links',
            field=models.ManyToManyField(blank=True, through='dashboard.SocialLink', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentsocial',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Content'),
        ),
        migrations.AddField(
            model_name='contentsocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Social'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_socials',
            field=models.ManyToManyField(blank=True, through='dashboard.ContentSocial', to='dashboard.Social'),
        ),
    ]
