# Generated by Django 2.0.1 on 2018-05-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='companies'),
        ),
    ]
