# Generated by Django 2.0.1 on 2018-02-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180213_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
