# Generated by Django 2.0.1 on 2018-02-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180208_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='media',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
