# Generated by Django 2.0.1 on 2018-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180212_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_socials',
            field=models.ManyToManyField(through='dashboard.ContentSocial', to='dashboard.Social'),
        ),
    ]
