# Generated by Django 2.0.1 on 2018-02-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180214_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
