# Generated by Django 2.0.1 on 2018-02-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_content_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media',
        ),
    ]
