# Generated by Django 2.0.1 on 2018-02-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20180214_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
