# Generated by Django 2.0.1 on 2018-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_company_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
