# Generated by Django 2.0.1 on 2018-05-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='slug',
            field=models.SlugField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
