# Generated by Django 2.0.1 on 2018-03-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_content_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='access_token_key',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
