# Generated by Django 2.0.1 on 2018-02-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_content_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
