# Generated by Django 2.0.1 on 2018-05-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_content_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Company'),
        ),
    ]
