# Generated by Django 2.0.1 on 2018-02-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180208_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='media',
        ),
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
