# Generated by Django 2.0.1 on 2018-02-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180208_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='photo',
        ),
        migrations.AddField(
            model_name='content',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
