# Generated by Django 2.0.1 on 2018-05-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20180503_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='account',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='content',
            name='account',
        ),
    ]
