# Generated by Django 2.0.1 on 2018-03-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_social_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(choices=[('profile', 'profile'), ('page', 'page'), ('group', 'group'), ('company', 'company')], default='profile', max_length=10),
        ),
    ]
