# Generated by Django 2.0.1 on 2018-03-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180309_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
