# Generated by Django 2.0.1 on 2018-02-08 17:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20180208_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='schedule_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
