# Generated by Django 2.0.1 on 2018-03-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20180316_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
