# Generated by Django 2.0.1 on 2018-02-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180208_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='schedule_at',
        ),
        migrations.AddField(
            model_name='content',
            name='is_schedule_now',
            field=models.BooleanField(default=False),
        ),
    ]
