# Generated by Django 2.0.1 on 2018-06-08 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0011_auto_20180503_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Team',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='company',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(choices=[('profile', 'profile'), ('page', 'page'), ('group', 'group'), ('team', 'team')], default='profile', max_length=10),
        ),
    ]
