# Generated by Django 2.0.1 on 2018-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180608_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='content',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='content',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='teams'),
        ),
    ]
