# Generated by Django 2.0.1 on 2018-02-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180209_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_auto_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
