# Generated by Django 2.0.1 on 2018-02-09 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_content_is_auto_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='schedule_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
