# Generated by Django 2.0.1 on 2018-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20180316_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.ImageField(blank=True, null=True, upload_to='contents'),
        ),
    ]
