# Generated by Django 2.0.1 on 2018-02-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_content_schedule_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='is_auto_schedule',
            new_name='is_schedule_auto',
        ),
    ]
