# Generated by Django 2.0.1 on 2018-03-25 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0015_auto_20180319_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='accounts',
        ),
        migrations.AddField(
            model_name='social',
            name='accounts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
