# Generated by Django 2.0.1 on 2018-02-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180209_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_schedule_auto',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_schedule_now',
        ),
        migrations.RemoveField(
            model_name='content',
            name='schedule_date_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='schedule_time_at',
        ),
    ]
