# Generated by Django 2.0.1 on 2018-03-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180325_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='accounts',
            new_name='account',
        ),
    ]
