# Generated by Django 2.0.1 on 2018-03-26 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0017_auto_20180326_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider', 'account')},
        ),
    ]
