# Generated by Django 2.0.1 on 2018-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20180326_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
