# Generated by Django 2.0.1 on 2018-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180209_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='schedule',
            field=models.CharField(choices=[(1, 'Now'), (2, 'Custom')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_schedule_at',
        ),
        migrations.RemoveField(
            model_name='content',
            name='is_schedule_now',
        ),
    ]
