# Generated by Django 2.0.1 on 2018-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20180209_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='schedule',
            field=models.CharField(choices=[('n', 'Now'), ('c', 'Custom')], max_length=1),
        ),
    ]
