# Generated by Django 2.0.1 on 2018-02-10 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20180210_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='schedule_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
