# Generated by Django 2.0.1 on 2018-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20180210_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
