# Generated by Django 2.0.1 on 2018-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_social_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='socials',
            field=models.ManyToManyField(to='dashboard.Social'),
        ),
    ]
