# Generated by Django 2.0.1 on 2018-02-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contents', '0002_auto_20180205_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='account',
        ),
        migrations.AddField(
            model_name='content',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
            preserve_default=False,
        ),
    ]
