# Generated by Django 2.0.1 on 2018-06-25 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='contents', validators=[django.core.validators.FileExtensionValidator(('mp4', 'png', 'jpg', 'jpeg', 'gif'))])),
                ('schedule', models.CharField(choices=[('now', 'Now'), ('date', 'Date')], default='now', max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('schedule_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.CharField(max_length=250)),
                ('provider', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('picture_url', models.URLField(blank=True)),
                ('access_token_key', models.TextField(max_length=1000)),
                ('access_token_secret', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('profile', 'profile'), ('page', 'page'), ('group', 'group'), ('company', 'company'), ('business', 'business')], default='profile', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'socials',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='socials',
            field=models.ManyToManyField(to='publisher.Social'),
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider', 'account', 'category')},
        ),
    ]
