# Generated by Django 2.0.1 on 2018-06-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20180616_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='schedule',
            field=models.CharField(choices=[('now', 'Now'), ('date', 'Date')], default='now', max_length=10),
        ),
    ]
