# Generated by Django 2.0.1 on 2018-06-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20180626_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='is_prompt',
        ),
    ]
