# Generated by Django 2.0.1 on 2018-06-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0003_auto_20180617_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
