# Generated by Django 2.0.1 on 2018-06-20 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_auto_20180617_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.RemoveField(
            model_name='team',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
