# Generated by Django 2.0.1 on 2018-06-26 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_remove_social_is_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(('mp4', 'png', 'jpg', 'jpeg', 'gif'))]),
        ),
    ]
