# Generated by Django 2.0.1 on 2018-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_auto_20180621_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(choices=[('profile', 'profile'), ('page', 'page'), ('group', 'group'), ('company', 'company'), ('business', 'business')], default='profile', max_length=10),
        ),
    ]
