# Generated by Django 2.0.1 on 2018-06-29 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_auto_20180626_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='content',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(('mp4', 'mov', 'png', 'jpg', 'jpeg', 'gif'))]),
        ),
        migrations.AlterField(
            model_name='content',
            name='schedule_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
