# Generated by Django 2.0.1 on 2018-06-29 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_auto_20180629_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='schedule_time_at',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
