# Generated by Django 2.0.1 on 2018-06-22 18:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0006_auto_20180622_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider', 'account', 'category')},
        ),
    ]
