# Generated by Django 2.0.1 on 2018-06-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_auto_20180623_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='editor',
            new_name='account',
        ),
    ]
