# Generated by Django 2.0.1 on 2018-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebook',
            old_name='users',
            new_name='accounts',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='users',
            new_name='accounts',
        ),
    ]
