# Generated by Django 2.0.1 on 2018-01-24 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.BigIntegerField()),
                ('provider', models.CharField(choices=[('twitter', 'Twitter')], max_length=30)),
                ('screen_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_picture_url', models.URLField()),
                ('access_token_key', models.TextField(max_length=1000)),
                ('access_token_secret', models.TextField()),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider')},
        ),
    ]
