# Generated by Django 2.0.1 on 2018-01-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facebook',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
                ('access_token_key', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('picture_url', models.URLField()),
                ('access_token_key', models.TextField(max_length=1000)),
                ('access_token_secret', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='social',
            name='users',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Facebook'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Twitter'),
            preserve_default=False,
        ),
    ]
