# Generated by Django 2.0.1 on 2018-01-23 17:48

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('accounts', '0004_auto_20180123_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialaccount',
            old_name='social_account_id',
            new_name='social_id',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('social_id', 'provider')},
        ),
    ]
