# Generated by Django 2.0.1 on 2018-01-23 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180123_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
