# Generated by Django 2.0.1 on 2018-01-23 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20180123_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialAccount',
            new_name='Social',
        ),
    ]
