# Generated by Django 2.0.1 on 2018-01-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180123_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='access_token_key',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='access_token_secret',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='display_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='profile_picture',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='screen_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
