# Generated by Django 2.0.1 on 2018-01-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180123_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='profile_picture',
            new_name='profile_picture_url',
        ),
    ]
