# Generated by Django 2.0.1 on 2018-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180123_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='social',
            name='social_id',
            field=models.BigIntegerField(),
        ),
    ]
