# Generated by Django 2.0.1 on 2018-01-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180123_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='social_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
