# Generated by Django 2.0.1 on 2018-01-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180123_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='provider',
            field=models.CharField(choices=[('twitter', 'Twitter')], max_length=30),
        ),
    ]
