# Generated by Django 2.0.1 on 2018-02-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_auto_20180205_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
