# Generated by Django 2.0.1 on 2018-02-06 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20180206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='schedule_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 6, 21, 1, 15, 279978, tzinfo=utc)),
        ),
    ]
