# Generated by Django 2.0.1 on 2018-02-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='user',
            new_name='account',
        ),
    ]
