# Generated by Django 2.0.1 on 2018-02-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180205_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='companies',
        ),
        migrations.AddField(
            model_name='social',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
            preserve_default=False,
        ),
    ]
