# Generated by Django 2.0.1 on 2018-02-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180206_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='company',
            field=models.ManyToManyField(blank=True, to='accounts.Company'),
        ),
    ]
