# Generated by Django 2.0.1 on 2018-06-25 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import megaphonely.billing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('stripe_customer_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('stripe_source_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stripe_last_four', models.CharField(max_length=4)),
                ('stripe_brand', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('name', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('socials', models.IntegerField()),
                ('contents', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('ends_at', models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PaymentMethod')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Plan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
