# Generated by Django 2.0.1 on 2018-04-02 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import megaphonely.billing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=50)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='trial', max_length=20)),
                ('subscription_id', models.CharField(blank=True, max_length=50)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('card', models.CharField(blank=True, max_length=20)),
                ('ends_at', models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
