# Generated by Django 2.0.1 on 2018-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('premium', 'Premium')], default='trial', max_length=20),
        ),
    ]
