# Generated by Django 2.0.1 on 2018-06-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180625_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.Plan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
    ]
