# Generated by Django 2.0.1 on 2018-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20180619_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='trial', max_length=20),
        ),
    ]
