# Generated by Django 2.0.1 on 2018-06-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180625_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='account',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
            preserve_default=False,
        ),
    ]
