# Generated by Django 2.0.1 on 2018-06-19 15:49

from django.db import migrations, models
import django.db.models.deletion
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20180619_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=50)),
                ('stripe_last_four', models.CharField(blank=True, max_length=4)),
                ('stripe_card', models.CharField(blank=True, max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20)),
                ('ends_at', models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_four',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
        ),
    ]
