# Generated by Django 2.0.1 on 2018-06-19 15:57

from django.db import migrations, models
import django.utils.timezone
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180619_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_customer_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_customer_id',
            new_name='customer_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='card',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='ends_at',
            field=models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
