# Generated by Django 2.0.1 on 2018-06-25 14:31

from django.db import migrations, models
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20180625_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
    ]
