# Generated by Django 2.0.1 on 2018-03-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20180306_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('expired', 'Expired'), ('free', 'Free'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='free', max_length=20),
        ),
    ]
