# Generated by Django 2.0.1 on 2018-03-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20180306_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
