# Generated by Django 2.0.1 on 2018-06-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0006_auto_20180619_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_source_id', models.CharField(max_length=100)),
                ('stripe_last_four', models.CharField(max_length=4)),
                ('stripe_card', models.CharField(max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='stripe_card',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='stripe_last_four',
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='stripe_customer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='stripe_subscription_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.StripePaymentMethod'),
            preserve_default=False,
        ),
    ]
