# Generated by Django 2.0.1 on 2018-06-19 16:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20180619_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer')),
            ],
        ),
        migrations.RenameField(
            model_name='stripepaymentmethod',
            old_name='stripe_card',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='stripepaymentmethod',
            old_name='stripe_last_four',
            new_name='last_four',
        ),
        migrations.RenameField(
            model_name='stripepaymentmethod',
            old_name='stripe_source_id',
            new_name='source_id',
        ),
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='stripe_customer_id',
            new_name='subscription_id',
        ),
        migrations.RemoveField(
            model_name='stripepaymentmethod',
            name='account',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='stripepaymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripepaymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stripepaymentmethod',
            name='stripe_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.StripeCustomer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripesubscription',
            name='stripe_customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='billing.StripeCustomer'),
            preserve_default=False,
        ),
    ]
