# Generated by Django 2.0.1 on 2018-06-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180619_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='payment_method',
            new_name='stripe_payment_method',
        ),
    ]
