# Generated by Django 2.0.1 on 2018-03-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_auto_20180306_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last4',
            new_name='last_four',
        ),
    ]
