# Generated by Django 2.0.1 on 2018-06-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20180619_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripepaymentmethod',
            old_name='card',
            new_name='brand',
        ),
    ]
