# Generated by Django 2.0.1 on 2018-03-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_auto_20180306_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='next_payment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
