# Generated by Django 2.0.1 on 2018-03-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_customer_next_payment_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='next_payment_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(default='trialing', max_length=50),
        ),
    ]
