# Generated by Django 2.0.1 on 2018-06-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20180619_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_source_id', models.CharField(max_length=100)),
                ('stripe_last_four', models.CharField(max_length=4)),
                ('stripe_brand', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='account',
        ),
        migrations.RemoveField(
            model_name='stripepaymentmethod',
            name='stripe_customer',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='stripe_customer',
        ),
        migrations.RemoveField(
            model_name='stripesubscription',
            name='stripe_payment_method',
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
        migrations.DeleteModel(
            name='StripePaymentMethod',
        ),
        migrations.DeleteModel(
            name='StripeSubscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PaymentMethod'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
        ),
    ]
