# Generated by Django 2.0.1 on 2018-03-08 14:03

from django.db import migrations, models
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_auto_20180308_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trial_ends_at',
            field=models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
    ]
