# Generated by Django 2.0.1 on 2018-03-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_customer_trial_ends_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='brand',
            new_name='card',
        ),
    ]
