# Generated by Django 2.0.1 on 2018-06-19 21:13

from django.db import migrations, models
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180619_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='ends_at',
            field=models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], default='free', max_length=20),
        ),
    ]
