# Generated by Django 2.0.1 on 2018-03-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_auto_20180308_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(max_length=50),
        ),
    ]
