# Generated by Django 2.0.1 on 2018-03-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0015_auto_20180308_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_ends_at', models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='trial_ends_at',
        ),
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_four',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(max_length=50),
        ),
    ]
