# Generated by Django 2.0.1 on 2018-06-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20180619_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='billing.Customer'),
        ),
    ]
