# Generated by Django 2.0.1 on 2018-03-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_auto_20180308_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('advanced', 'Advanced')], default='trial', max_length=20),
        ),
    ]
