# Generated by Django 2.0.1 on 2018-03-08 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_auto_20180308_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='trial_ends_at',
            new_name='ends_at',
        ),
        migrations.AddField(
            model_name='trial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
