# Generated by Django 2.0.1 on 2018-06-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20180624_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_pricing_plan_id',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('free', 'Free'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
