# Generated by Django 2.0.1 on 2018-03-16 20:52

from django.db import migrations, models
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_auto_20180308_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trial',
            name='ends_at',
            field=models.DateField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
    ]
