# Generated by Django 2.0.1 on 2018-03-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_auto_20180316_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
