# Generated by Django 2.0.1 on 2018-06-24 13:36

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('billing', '0020_auto_20180624_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='id',
            new_name='name',
        ),
    ]
