# Generated by Django 2.0.1 on 2018-03-28 17:40

from django.db import migrations, models
import megaphonely.billing.models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_trial_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='account',
        ),
        migrations.AddField(
            model_name='customer',
            name='ends_at',
            field=models.DateTimeField(default=megaphonely.billing.models.get_trial_ends_at),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
