# Generated by Django 2.0.1 on 2018-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_auto_20180328_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('advanced', 'Advanced')], default='trial', max_length=20),
        ),
    ]
