# Generated by Django 2.0.1 on 2018-02-05 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_id', models.BigIntegerField()),
                ('provider', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('picture_url', models.URLField(blank=True)),
                ('access_token_key', models.TextField(max_length=1000)),
                ('access_token_secret', models.TextField(blank=True)),
                ('accounts', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='accounts',
        ),
        migrations.DeleteModel(
            name='Facebook',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
        migrations.AlterUniqueTogether(
            name='social',
            unique_together={('social_id', 'provider')},
        ),
    ]
