# Generated by Django 2.0.1 on 2018-02-07 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='social',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='social',
            name='accounts',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
    ]
