# Generated by Django 2.0.1 on 2018-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
