# Generated by Django 2.0.1 on 2018-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
