# Generated by Django 2.0.1 on 2018-02-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180205_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='company',
        ),
        migrations.AddField(
            model_name='social',
            name='company',
            field=models.ManyToManyField(to='accounts.Company'),
        ),
    ]
