# Generated by Django 2.0.1 on 2018-02-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180207_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
